name: sleep-staging
channels:
    - pytorch
dependencies:
    - cudatoolkit=11.0.*
    - h5py
    - joblib
    - matplotlib=3.3.2
    - numpy=1.19.2
    - pandas=1.2.1
    - pip=20.3.3
    - pytorch=1.7.0
    - python=3.7.9
    - scipy=1.5.2
    - scikit-learn=0.23.2
    - torchaudio=0.7.0
    - torchvision=0.8.1
    - tqdm
    - xmltodict
    - pip:
        - librosa==0.8.0
        - mne==0.22.1
        - pytorch-lightning==1.0.4
