import os
import tempfile
from time import sleep

# fmt: off
JOBS = [
    # ('train_massc', 'python train.py --model_type massc --max_epochs 50 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --optimizer adam --learning_rate 2e-4 --weight_decay 2e-4 --scaling robust'),
    # ('train_utime', 'python train.py --model_type utime --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --n_records 1000 --scaling robust'),
    # ('train_utime', 'python train.py --model_type utime --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --scaling robust'),
    # ('train_utime_n500', 'python train.py --model_type utime --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --n_records 500 --scaling robust'),
    # ('train_utime_n1500', 'python train.py --model_type utime --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --n_records 1500 --scaling robust'),
    # ('train_utime_n2000', 'python train.py --model_type utime --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --n_records 2000 --scaling robust'),
    # ('train_massc_stablesleep', 'python train.py --model_type massc --max_epochs 50 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --scaling robust --data_dir data/full_length/ssc_wsc/raw/train --adjustment 30'),
    # ('massc', 'python train.py --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 0 --optimizer adam --learning_rate 1e-3 --earlystopping_patience 10'),
    # ('massc_nornn', 'python train.py --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 0 --optimizer adam --learning_rate 1e-3 --n_rnn_units 0 --earlystopping_patience 50'),
    # ('massc_15', 'python train.py --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-3 --earlystopping_patience 10'),
    # ('massc_nornn_15', 'python train.py --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-3 --n_rnn_units 0 --earlystopping_patience 50'),
    # ('massc_30', 'python train.py --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --scaling robust --data_dir data/ssc_wsc/radw/5min --adjustment 30 --optimizer adam --learning_rate 1e-3 --earlystopping_patience 10'),
    # ('massc_nornn_30', 'python train.py --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 30 --optimizer adam --learning_rate 1e-3 --n_rnn_units 0 --earlystopping_patience 50'),
    # ('massc_rnn', 'python train.py --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 0 --optimizer adam --learning_rate 1e-3 --earlystopping_patience 50'),
    # ('massc_rnn_adj30', 'python train.py --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 30 --optimizer adam --learning_rate 1e-3 --earlystopping_patience 50'),
    # ('massc_rnn_adj15', 'python train.py --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-3 --earlystopping_patience 50'),

    # ('cv1', 'python train.py --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-3 --earlystopping_patience 25 --cv -3 --cv_idx 0 --n_rnn_units 0'),
    # ('cv2', 'python train.py --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-3 --earlystopping_patience 25 --cv -3 --cv_idx 1 --n_rnn_units 0'),
    # ('cv3', 'python train.py --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-3 --earlystopping_patience 25 --cv -3 --cv_idx 2 --n_rnn_units 0'),
    # ('cv1', 'python train.py --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --cv 3 --cv_idx 0 --n_rnn_units 0'),
    # ('cv2', 'python train.py --model_type massc --max_epochs 100 --gpus 1 --distributed_backend ddp --n_jobs -1 --n_workers 5 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --cv 3 --cv_idx 1 --n_rnn_units 0'),
    # ('cv3', 'python train.py --model_type massc --max_epochs 100 --gpus 1 --distributed_backend ddp --n_jobs -1 --n_workers 5 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --cv 3 --cv_idx 2 --n_rnn_units 0'),
    # ('cv1', 'python train.py --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 16 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --cv -3 --cv_idx 0 --resume_from_checkpoint experiments/massc/cv1/20201029_081358/last.ckpt'),
    # ('cv3', 'python train.py --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 16 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --cv -3 --cv_idx 2 --resume_from_checkpoint experiments/massc/cv3/20201029_074212/last.ckpt'),
    # ('cv1', 'python train.py --model_type massc --max_epochs 100 --gpus 1 --n_jobs -1 --n_workers 20 --batch_size 64 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --cv 3 --cv_idx 0 --n_rnn_units 0 --name cv1 --precision 16'),
    # ('cv2', 'python train.py --model_type massc --max_epochs 100 --gpus 1 --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --cv 3 --cv_idx 1 --n_rnn_units 0 --precision 16'),
    # ('cv3', 'python train.py --model_type massc --max_epochs 100 --gpus 1 --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --cv 3 --cv_idx 2 --n_rnn_units 0 --precision 16'),
    # ('kw5/cv1', 'python train.py --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --n_rnn_units 0 --kernel_size 5 --cv 5 --cv_idx 0'),
    # ('kw5_cv2', 'python train.py --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --n_rnn_units 0 --kernel_size 5 --cv 5 --cv_idx 1'),
    # ('kw5_cv3', 'python train.py --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --n_rnn_units 0 --kernel_size 5 --cv 5 --cv_idx 2'),
    # ('kw5_cv4', 'python train.py --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --n_rnn_units 0 --kernel_size 5 --cv 5 --cv_idx 3'),
    # ('kw5_cv5', 'python train.py --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --n_rnn_units 0 --kernel_size 5 --cv 5 --cv_idx 4'),
    # ('kw9_cv1', 'python train.py --kernel_size 9 --cv 5 --cv_idx 0 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --n_rnn_units 0'),
    # ('kw9_cv2', 'python train.py --kernel_size 9 --cv 5 --cv_idx 1 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --n_rnn_units 0'),
    # ('kw9_cv3', 'python train.py --kernel_size 9 --cv 5 --cv_idx 2 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --n_rnn_units 0'),
    # ('kw9_cv4', 'python train.py --kernel_size 9 --cv 5 --cv_idx 3 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --n_rnn_units 0'),
    # ('kw9_cv5', 'python train.py --kernel_size 9 --cv 5 --cv_idx 4 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --n_rnn_units 0'),
    # ('kw5', 'python train.py --kernel_size 5 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --n_rnn_units 0'),
    # ('kw7', 'python train.py --kernel_size 7 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --n_rnn_units 0'),
    # ('kw9', 'python train.py --kernel_size 9 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --n_rnn_units 0'),
    # ('kw11', 'python train.py --kernel_size 11 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --n_rnn_units 0'),
    # ('kw13', 'python train.py --kernel_size 13 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --n_rnn_units 0'),
    # ('cv2_cvidx0', 'python train.py --cv 2 --cv_idx 0 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --n_rnn_units 0'),
    # ('cv2_cvidx1', 'python train.py --cv 2 --cv_idx 1 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --n_rnn_units 0'),
    # ('masscv2', 'python train.py --model_type massc_v2 --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('cv2_cvidx0', 'python train.py --cv 2 --cv_idx 0--model_type massc_v2 --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('cv-3_cvidx0', 'python train.py --cv -3 --cv_idx 0 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --n_rnn_units 0'),
    # ('cv-3_cvidx1', 'python train.py --cv -3 --cv_idx 1 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --n_rnn_units 0'),
    # ('cv-3_cvidx2', 'python train.py --cv -3 --cv_idx 2 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 5e-4 --earlystopping_patience 25 --n_rnn_units 0'),
    # ('cv-4_cvidx0', 'python train.py --cv -4 --cv_idx 0 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-4 --earlystopping_patience 25 --n_rnn_units 0'),
    # ('cv-4_cvidx1', 'python train.py --cv -4 --cv_idx 1 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-4 --earlystopping_patience 25 --n_rnn_units 0'),
    # ('cv-4_cvidx2', 'python train.py --cv -4 --cv_idx 2 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-4 --earlystopping_patience 25 --n_rnn_units 0'),
    # ('cv-4_cvidx3', 'python train.py --cv -4 --cv_idx 3 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-4 --earlystopping_patience 25 --n_rnn_units 0'),
    # ('cv3_cvidx0', 'python train.py --cv 3 --cv_idx 0 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-4 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('cv3_cvidx1', 'python train.py --cv 3 --cv_idx 1 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-4 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('cv3_cvidx2', 'python train.py --cv 3 --cv_idx 2 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-4 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('cv1_cvidx0', 'python train.py --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-4 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('kw3', 'python train.py --kernel_size 3 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('kw5', 'python train.py --kernel_size 5 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('kw7', 'python train.py --kernel_size 7 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('kw9', 'python train.py --kernel_size 9 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('kw11', 'python train.py --kernel_size 11 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('kw13', 'python train.py --kernel_size 13 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('kw15', 'python train.py --kernel_size 15 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('kw17', 'python train.py --kernel_size 17 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('cv3_cvidx0', 'python train.py --cv 3 --cv_idx 0 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('cv3_cvidx1', 'python train.py --cv 3 --cv_idx 1 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('cv3_cvidx2', 'python train.py --cv 3 --cv_idx 2 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('cv2_cvidx0', 'python train.py --cv 2 --cv_idx 0 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('cv2_cvidx1', 'python train.py --cv 2 --cv_idx 1 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('cv-3_cvidx0', 'python train.py --cv -3 --cv_idx 0 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('cv-3_cvidx1', 'python train.py --cv -3 --cv_idx 1 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('cv-3_cvidx2', 'python train.py --cv -3 --cv_idx 2 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('cv-4_cvidx0', 'python train.py --cv -4 --cv_idx 0 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('cv-4_cvidx1', 'python train.py --cv -4 --cv_idx 1 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('cv-4_cvidx2', 'python train.py --cv -4 --cv_idx 2 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('cv-4_cvidx3', 'python train.py --cv -4 --cv_idx 3 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0'),
    # ('s01', 'python train.py --model_type stages --model_name ac_rh_lh_lstm_01 --gpus 2 --distributed_backend ddp --n_jobs -1 --n_workers 10'),
    # ('kw19', 'python train.py --kernel_size 19 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0 --lr_reduce_patience 10'),
    # ('kw21', 'python train.py --kernel_size 21 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0 --lr_reduce_patience 10'),
    # ('kw23', 'python train.py --kernel_size 23 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0 --lr_reduce_patience 10'),
    # ('kw25', 'python train.py --kernel_size 25 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0 --lr_reduce_patience 10'),
    # ('kw27', 'python train.py --kernel_size 27 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0 --lr_reduce_patience 10'),
    # ('kw29', 'python train.py --kernel_size 29 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0 --lr_reduce_patience 10'),
    # ('kw31', 'python train.py --kernel_size 31 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0 --lr_reduce_patience 10'),
    # ('kw33', 'python train.py --kernel_size 33 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0 --lr_reduce_patience 10'),
    # ('kw35', 'python train.py --kernel_size 35 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0 --lr_reduce_patience 10'),
    # ('kw37', 'python train.py --kernel_size 35 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0 --lr_reduce_patience 10'),
    # ('kw39', 'python train.py --kernel_size 35 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0 --lr_reduce_patience 10'),
    # ('kw41', 'python train.py --kernel_size 35 --model_type massc --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --n_rnn_units 0 --lr_reduce_patience 10'),
    # ('att15', 'python train.py --model_type massc_attention --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --lr_reduce_patience 10 --eval_frequency_sec 15'),
    # ('att30', 'python train.py --model_type massc_attention --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 50 --lr_reduce_patience 10 --eval_frequency_sec 30'),
    # ('avg_kw3_residual', 'python train.py --model_type massc_average --max_epochs 100 --gpus 2 --distributed_backend ddp --n_jobs -1 --n_workers 10 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 25 --lr_reduce_patience 10 --kernel_size 3 --block_type residual --filter_base 8'),
    # ('avg_kw21_residual', 'python train.py --model_type massc_average --max_epochs 100 --gpus 2 --distributed_backend ddp --n_jobs -1 --n_workers 10 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 25 --lr_reduce_patience 10 --kernel_size 21 --block_type residual --filter_base 8'),
    # ('avg_kw3_bottleneck', 'python train.py --model_type massc_average --max_epochs 100 --gpus 2 --distributed_backend ddp --n_jobs -1 --n_workers 10 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 25 --lr_reduce_patience 10 --kernel_size 3 --block_type bottleneck'),
    # ('avg_kw21_bottleneck', 'python train.py --model_type massc_average --max_epochs 100 --gpus 2 --distributed_backend ddp --n_jobs -1 --n_workers 10 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 15 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 25 --lr_reduce_patience 10 --kernel_size 21 --block_type bottleneck'),
    # ('avg_kw21_rnn128', 'python train.py --model_type massc_average --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 0 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 25 --lr_reduce_patience 10 --kernel_size 21 --n_rnn_units 128 --n_rnn_layers 1 --rnn_bidirectional'),
    ('avg_kw3_rnn128', 'python train.py --model_type massc_average --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 0 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 25 --lr_reduce_patience 10 --kernel_size 3 --n_rnn_units 128 --n_rnn_layers 1 --rnn_bidirectional'),
    ('avg_kw21_rnn128_cyclic', 'python train.py --model_type massc_average --max_epochs 100 --gpus 4 --distributed_backend ddp --n_jobs -1 --n_workers 20 --batch_size 32 --scaling robust --data_dir data/ssc_wsc/raw/5min --adjustment 0 --optimizer adam --learning_rate 1e-5 --earlystopping_patience 25 --kernel_size 21 --n_rnn_units 128 --n_rnn_layers 1 --rnn_bidirectional --lr_scheduler cycliclr --max_lr 2e-2 --step_size_up 16000 --base_lr 1e-4'),
]
# fmt: on


def submit_job(jobname, experiment):

    content = """#!/bin/bash
#
#SBATCH --job-name={0}
#SBATCH -p mignot,owners,gpu
#SBATCH --time=2-00:00
#SBATCH --cpus-per-task=20
#SBATCH --gpus 4
#SBATCH --output=/home/users/alexno/sleep-staging/logs/{0}.out
#SBATCH --error=/home/users/alexno/sleep-staging/logs/{0}.err
##################################################

source $PI_HOME/miniconda3/bin/activate
conda activate pt1.7
cd $HOME/sleep-staging

{1} --name {0}
"""
    with tempfile.NamedTemporaryFile(delete=False) as j:
        j.write(content.format(jobname, experiment).encode())
    os.system("sbatch {}".format(j.name))


if __name__ == "__main__":

    for job in JOBS:
        submit_job(job[0], job[1])
        sleep(1)

    print("All jobs have been submitted!")
